DROP DATABASE IF EXISTS progetto_partite;
CREATE DATABASE IF NOT EXISTS progetto_partite;
USE progetto_partite;

CREATE TABLE Squadre(
id_squadra INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(30) NOT NULL,
logo_squadra VARCHAR(40) NOT NULL,
partite_giocate INT DEFAULT 0,
vittorie INT DEFAULT 0,
pareggi INT DEFAULT 0,
sconfitte INT DEFAULT 0,
goal_fatti INT DEFAULT 0,
goal_subiti INT DEFAULT 0,
differenza_reti INT DEFAULT 0,
numero_punti INT DEFAULT 0);

CREATE TABLE Risultati(
id_risultato INT AUTO_INCREMENT PRIMARY KEY,
id_squadra_casa INT NOT NULL,
id_squadra_ospite INT NOT NULL,
numero_goal_casa INT NOT NULL,
numero_goal_ospite INT NOT NULL,
image_partita VARCHAR(40) NOT NULL,
link_highlights VARCHAR(120) NOT NULL,
FOREIGN KEY (id_squadra_casa) REFERENCES Squadre(id_squadra)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (id_squadra_ospite) REFERENCES Squadre(id_squadra)
ON DELETE CASCADE ON UPDATE CASCADE);

INSERT 
INTO Squadre(nome, logo_squadra, partite_giocate, vittorie, pareggi, sconfitte, goal_fatti, goal_subiti, differenza_reti, numero_punti)
VALUES	("Atalanta", "loghi/Logo_Atalanta.png", 36, 20, 6, 10, 67, 39, 28, 66),
		("Bologna", "loghi/Logo_Bologna.png", 38, 18, 14, 6, 54, 32, 22, 68),
        ("Cagliari", "loghi/Logo_Cagliari.png", 38, 8, 12, 18, 42, 68, -26, 36),
        ("Empoli", "loghi/Logo_Empoli.png", 37, 8, 9, 20, 27, 53, -26, 33),
        ("Fiorentina", "loghi/Logo_Fiorentina.png", 37, 16, 9, 12, 58, 44, 14, 57),
        ("Frosinone", "loghi/Logo_Frosinone.png", 37, 8, 11, 18, 44, 68, -24, 35),
        ("Genoa", "loghi/Logo_Genoa.png", 38, 12, 13, 13, 45, 45, 0, 49),
        ("Inter", "loghi/Logo_Inter.png", 37, 29, 6, 2, 87, 20, 67, 93),
        ("Juventus", "loghi/Logo_Juventus.png", 38, 19, 14, 5, 54, 31, 23, 71),
        ("Lazio", "loghi/Logo_Lazio.png", 37, 18, 6, 13, 48, 38, 10, 60),
        ("Lecce", "loghi/Logo_Lecce.png", 37, 8, 13, 16, 32, 54, -22, 37),
        ("Milan", "loghi/Logo_Milan.png", 38, 22, 9, 7, 76, 49, 27, 75),
        ("Monza", "loghi/Logo_Monza.png", 38, 11, 12, 15, 39, 51, -12, 45),
        ("Napoli", "loghi/Logo_Napoli.png", 37, 13, 13, 11, 55, 48, 7, 52),
        ("Roma", "loghi/Logo_Roma.png", 37, 18, 9, 10, 64, 44, 20, 63),
        ("Salernitana", "loghi/Logo_Salernitana.png", 38, 2, 11, 25, 32, 81, -49, 17),
        ("Sassuolo", "loghi/Logo_Sassuolo.png", 37, 7, 8, 22, 42, 74, -32, 29),
        ("Torino", "loghi/Logo_Torino.png", 37, 13, 14, 10, 36, 33, 3, 53),
        ("Udinese", "loghi/Logo_Udinese.png", 37, 5, 19, 13, 36, 53, -17, 34),
        ("Hellas Verona", "loghi/Logo_Hellas Verona.png", 37, 9, 10, 18, 36, 49, -13, 37);
        
        
INSERT
INTO Risultati(id_squadra_casa, id_squadra_ospite, numero_goal_casa, numero_goal_ospite, image_partita, link_highlights)
VALUES	
		-- PRIMA GIORNATA
		(6, 14, 1, 3, "../../images/frosinone_napoli.jpeg", "https://www.youtube.com/watch?v=K4VydrWi7Uw&pp=ygUURnJvc2lub25lLU5hcG9saSAxLTM%3D"),
		(4, 20, 0, 1, "../../images/empoli_verona.jpg", "https://www.youtube.com/watch?v=GTTsixW_pe4"),
		(7, 5, 1, 4, "../../images/genoa_fiorentina.jpg", "https://youtu.be/1g7ml8nvMy8?si=93c6pyj4-BdHQpCU"),
		(8, 13, 2, 0, "../../images/inter_monza.jpg", "https://youtu.be/mu5iZLSitWA?si=ED7zeJmSdqvc5fO6"),
		(17, 1, 0, 2, "../../images/sassuolo_atalanta.jpg", "https://www.youtube.com/watch?v=JvW3hZh-d6U&pp=ygUVc2Fzc3VvbG8gYXRhbGFudGEgMCAy"),
		(15, 16, 2, 2, "../../images/roma_salernitana.jpg", "https://youtu.be/t3gTGakSEj8?si=IU4XTcsXKVqZo7YC"),
		(11, 10, 2, 1, "../../images/lecce_lazio.jpg", "https://youtu.be/1h6o8gmVM78?si=Qi5MwV3Cy7Akfyx0"),
		(19, 9, 0, 3, "../../images/udinese_juventus.jpg", "https://youtu.be/eqAyK78Gyog?si=HeKcVvWIUf5yq0Mk"),
		(18, 3, 0, 0, "../../images/torino_cagliari.jpg", "https://youtu.be/TLyAOSP1vuw?si=artSbIx49tL7zHkr"),
		(2, 12, 0, 2, "../../images/bologna_milan.jpg", "https://youtu.be/YKIACBEBKz8?si=cX5mTq2H-aqSbFNP"),
        
        -- SECONDA GIORNATA
        (6, 1, 2, 1, "../../images/frosinone_atalanta.jpg", "https://www.youtube.com/watch?v=DsMVNTHP1cU&pp=ygUWZnJvc2lub25lIGF0YWxhbnRhIDIgMQ%3D%3D"),
		(13, 4, 2, 0, "../../images/monza_empoli.jpg", "https://youtu.be/EG2lNdAv0e8?si=YXeIFTS9Ozz0iJ15"),
		(20, 15, 2, 1, "../../images/verona_roma.jpg", "https://www.youtube.com/watch?v=hkeSqA4Go-k"),
		(12, 18, 4, 1, "../../images/milan_torino.jpg", "https://youtu.be/fKaGtVLVONs?si=69HuYxdqgcXLNoxt"),
		(9, 2, 1, 1, "../../images/juventus_bologna.jpg", "https://youtu.be/8DkFjTmYGPA?si=3plCPQ4z7s-C9PVw"),
		(5, 11, 2, 2, "../../images/fiorentina_lecce.jpg", "https://youtu.be/LcWIEPSMG8g?si=uNeDQoyOK629paBN"),
		(10, 7, 0, 1, "../../images/lazio_genoa.jpg", "https://youtu.be/eX0mC5iq-Z0?si=EjVzCQWHIVInjou6"),
		(14, 17, 2, 0, "../../images/napoli_sassuolo.jpg", "https://youtu.be/NJ-5b7T7a4o?si=_newvl1mFYHm1hB5"),
		(16, 19, 1, 1, "../../images/salernitana_udinese.jpg", "https://youtu.be/cGUJE0bSWD8?si=EmPet431p7YJxeyo"),
		(3, 8, 0, 2, "../../images/cagliari_inter.jpg", "https://youtu.be/QJspB9JTP9E?si=Ii9vCIjO8xxD2aWa"),
        
        -- TERZA GIORNATA
        (17, 20, 3, 1, "../../images/sassuolo_verona.jpg", "https://youtu.be/WCrmjwBSv7U?si=E5H9sPMuADvhEvet"),
		(15, 12, 1, 2, "../../images/roma_milan.jpg", "https://youtu.be/-UoyiB6e9Ok?si=M-NGjDzqmTKL56By"),
		(19, 6, 0, 0, "../../images/udinese_frosinone.jpg", "https://youtube.com/watch?v=uduftW2LW_Q&feature=shared"),
		(2, 3, 2, 1, "../../images/bologna_cagliari.jpg", "https://youtu.be/J1dXjSFBdL4?si=ZZg3DmyqMP4An1DV"),
		(14, 10, 1, 2, "../../images/napoli_lazio.jpg", "https://youtu.be/OXDvLut8r_0?si=-K-3Lrx_bpXiAepg"),
		(1, 13, 3, 0, "../../images/atalanta_monza.jpg", "https://www.youtube.com/watch?v=7Q4v0trFaM8&pp=ygUSYXRhbGFudGEgbW9uemEgMyAw"),
		(8, 5, 4, 0, "../../images/inter_fiorentina.jpg", "https://youtu.be/oOWsMEl-Sak?si=3SPlm8A2hhPzfMal"),
		(18, 7, 1, 0, "../../images/torino_genoa.jpg", "https://youtu.be/cbcDyEWP6xE?si=0wdq7eT_TYsg2-ob"),
		(4, 9, 0, 2, "../../images/empoli_juventus.jpg", "https://youtu.be/g6YTmUBo7ZU?si=X_p_61JhH-VF74sc"),
        (11, 16, 2, 0, "../../images/lecce_salernitana.jpg", "https://youtu.be/7DtstAXHJZU?si=PBIbsL_CGxOtwdHO"),
        
        -- QUARTA GIORNATA
        (9, 10, 3, 1, "../../images/juventus_lazio.jpg", "https://youtu.be/LHNynKbGi4g?si=hC19DX-48PWh0YTv"),
		(8, 12, 5, 1, "../../images/inter_milan.jpg", "https://youtu.be/JYyQKl2LbJI?si=JaZFed_-NWPJo-5b"),
		(7, 14, 2, 2, "../../images/genoa_napoli.jpg", "https://youtu.be/REHlwccOIMc?si=EQABNJpikRxu7Ctv"),
		(3, 19, 0, 0, "../../images/cagliari_udinese.jpg", "https://youtu.be/k7cWu0Ik6YM?si=GbT9dxkzQI86Q0Wr"),
		(13, 11, 1, 1, "../../images/monza_lecce.jpg", "https://youtu.be/m5DyvolYhc8?si=ZNcbfaMF9zWJtN1M"),
		(6, 17, 4, 2, "../../images/frosinone_sassuolo.jpg", "https://youtube.com/watch?v=eA0feyEO7D8&feature=shared"),
		(5, 1, 3, 2, "../../images/fiorentina_atalanta.jpg", "https://youtu.be/GZLSCWn7Uy8?si=gJNEHQCJ-3qgeIKu"),
		(15, 4, 7, 0, "../../images/roma_empoli.jpg", "https://youtu.be/vSkeb9XFesE?si=vQgJVDKxOtSODoTH"),
		(16, 18, 0, 3, "../../images/salernitana_torino.jpg", "https://youtu.be/hwaj2dLc5rs?si=N6dQRZjziT0ucO6T"),
		(20, 2, 0, 0, "../../images/verona_bologna.jpg", "https://youtu.be/GeYwFfxtdqM?si=4C7vnzyNJLSYDUN7"),
        
        -- QUINTA GIORNATA
        (16, 6, 1, 1, "../../images/salernitana_frosinone.jpg", "https://youtu.be/_hTA6D8ah7g?si=jGe1tNVaOUUTcs4r"),
		(11, 7, 1, 0, "../../images/lecce_genoa.jpg", "https://youtu.be/7wGw2Rgaivo?si=yQer-WpSdQG_ue5V"),
		(12, 20, 1, 0, "../../images/milan_verona.jpg", "https://youtu.be/mB7syyAfNtg?si=TJm24bFPIDu94lXb"),
		(17, 9, 4, 2, "../../images/sassuolo_juventus.jpg", "https://youtu.be/J2sXJhKQa1s?si=T5LkBQ5prFJmchRM"),
		(10, 13, 1, 1, "../../images/lazio_monza.jpg", "https://youtu.be/1qydRHbFxKo?si=3xzl4Efm10kkyfSS"),
		(4, 8, 0, 1, "../../images/empoli_inter.jpg", "https://youtu.be/yh5MrNEgvFw?si=-urwPrPGe8LDE99h"),
		(1, 3, 2, 0, "../../images/atalanta_cagliari.jpg", "https://youtu.be/Qi7J0yCT4H8?si=3w4tHZ8MN3N0h1eW"),
		(19, 5, 0, 2, "../../images/udinese_fiorentina.jpg", "https://youtu.be/nC_2drYcGVI?si=zZo6szj94c-xY6Xl"),
		(2, 14, 0, 0, "../../images/bologna_napoli.jpg", "https://youtu.be/C-ocGzVlEgQ?si=6TybBtij2I-o5Hpc"),
		(18, 15, 1, 1, "../../images/torino_roma.jpg", "https://youtu.be/gOpuK0CHQhQ?si=gdq4_YeD1nuSc8y7"),
        
        -- SESTA GIORNATA
        (9, 11, 1, 0, "../../images/juventus_lecce.jpg", "https://youtu.be/j22fe30BJZ8?si=zkJtiDOkCGIGqMEo"),
		(3, 12, 1, 3, "../../images/cagliari_milan.jpg", "https://youtu.be/5jXGMhgzXpU?si=5-xWiorrzi-OOVeM"),
		(4, 16, 1, 0, "../../images/empoli_salernitana.jpg", "https://youtu.be/WJ4hde-Mrww?si=YniClGPFlS2bSDI_"),
		(20, 1, 0, 1, "../../images/verona_atalanta.jpg", "https://youtu.be/0fWHLmiznTw?si=bEg-gPr4q5RJtOfy"),
		(14, 19, 4, 1, "../../images/napoli_udinese.jpg", "https://youtu.be/8xQOhOlH5b4?si=Dbjyutk5sRu19Gv_"),
		(8, 17, 1, 2, "../../images/inter_sassuolo.jpg", "https://youtu.be/duICg95HiZ8?si=kkrjCzFEzhTodS0S"),
		(10, 18, 2, 0, "../../images/lazio_torino.jpg", "https://youtu.be/pzQYmRPD_lo?si=xh3bxt35RQPyXIy4"),
		(6, 5, 1, 1, "../../images/frosinone_fiorentina.jpg", "https://youtu.be/-ET_U2U9qTQ?si=pN0j-R6x6U_U00lh"),
		(13, 2, 0, 0, "../../images/monza_bologna.jpg", "https://youtu.be/MdY04TA7nkk?si=gaQhAAsJnNWKiZ1D"),
		(7, 15, 4, 1, "../../images/genoa_roma.jpg", "https://youtu.be/qG7kNI_hcno?si=FI8dxRDo251AClcD"),
        
        -- SETTIMA GIORNATA
        (11, 14, 0, 4, "../../images/lecce_napoli.jpg", "https://youtu.be/Vy6Ox8jRUgs?si=k_VuYj4Z0NwtBO6a"),
		(12, 10, 2, 0, "../../images/milan_lazio.jpg", "https://youtu.be/l3-Sq7Uk3T4?si=-wWZnTcivxvfxYts"),
		(16, 8, 0, 4, "../../images/salernitana_inter.jpg", "https://youtu.be/mNEJem2rz3s?si=GqwopVwWamfh1imO"),
		(2, 4, 3, 0, "../../images/bologna_empoli.jpg", "https://youtu.be/yHal20uvkWs?si=6Urs6GiI6o0-3z84"),
		(19, 7, 2, 2, "../../images/udinese_genoa.jpg", "https://youtu.be/iEHZJJ4T-qM?si=O2TpAuKC_7k44u-j"),
		(1, 9, 0, 0, "../../images/atalanta_juventus.jpg", "https://youtu.be/bAE08BgAVRc?si=9aRxLv2u4UEeWnmb"),
		(15, 6, 2, 0, "../../images/roma_frosinone.jpg", "https://youtu.be/Wv_iX8jQOi0?si=8HkRulSrzXJof0DA"),
		(17, 13, 0, 1, "../../images/sassuolo_monza.jpg", "https://youtu.be/HEDPYMYh1_k?si=9cy38UcLYLTFURSf"),
		(18, 20, 0, 0, "../../images/torino_verona.jpg", "https://youtu.be/f8Ta90GvqeI?si=QlxeK8qEXxoYkOqG"),
		(5, 3, 3, 0, "../../images/fiorentina_cagliari.jpg", "https://youtu.be/6_MRFw0vsnc?si=3TH5SPksjXo1G1CX"),
        
        -- OTTAVA GIORNATA
        (4, 19, 0, 0, "../../images/empoli_udinese.jpg", "https://youtu.be/WT-l5DHrs48?si=Ul4ouR9m25PEA6_C"),
		(11, 17, 1, 1, "../../images/lecce_sassuolo.jpg", "https://youtu.be/q07xBwGxHBk?si=Wbh7_n04ePo3avFK"),
		(8, 2, 2, 2, "../../images/inter_bologna.jpg", "https://youtu.be/_U-Oj5T9TW0?si=SH5IDAODi9pkNBT6"),
		(9, 18, 2, 0, "../../images/juventus_torino.jpg", "https://youtu.be/Jdheb1oV4X8?si=LWWjB483zteWuGNg"),
		(7, 12, 0, 1, "../../images/genoa_milan.jpg", "https://youtu.be/UGKhYwy37P4?si=A2nymeen-UesNguP"),
		(13, 16, 3, 0, "../../images/monza_salernitana.jpg", "https://youtu.be/vo7907eV1lQ?si=oMRoMkrx5O0J6bpo"),
		(10, 1, 3, 2, "../../images/lazio_atalanta.jpg", "https://www.youtube.com/watch?v=8FjEHaYkCB4&pp=ygUbbGF6aW8gYXRhbGFudGEgcmFkaW9jcm9uYWNh"),
		(6, 20, 2, 1, "../../images/frosinone_verona.jpg", "https://youtu.be/uMF5Mkvso3A?si=JPU4N6poAsFiQiD6"),
		(3, 15, 1, 4, "../../images/cagliari_roma.jpg", "https://youtu.be/UqwB_KNuxOk?si=1yKzKuGcaGRT21Bb"),
		(14, 5, 1, 3, "../../images/napoli_fiorentina.jpg", "https://youtu.be/HWvae5lAf0s?si=3Sh8GZSqPhjV1ViL"),
        
        -- NONA GIORNATA
        (20, 14, 1, 3, "../../images/verona_napoli.jpg", "https://youtu.be/169LnDdrLoQ?si=AAubXWj8W8r8QBlH"),
		(18, 8, 0, 3, "../../images/torino_inter.jpg", "https://youtu.be/uFUuPXAIRBU?si=n9p1BrX2RAlw2MaU"),
		(17, 10, 0, 2, "../../images/sassuolo_lazio.jpg", "https://youtu.be/Bq2qdoLx_Es?si=mqsPNoFRYsDnx6M9"),
		(15, 13, 1, 0, "../../images/roma_monza.jpg", "https://youtu.be/x9b6vzgmdWc?si=gJcKkfI5SiXVxlzP"),
		(16, 3, 2, 2, "../../images/salernitana_cagliari.jpg", "https://youtu.be/bp0yAV9jHyI?si=K7uicXZ-mgeYisZI"),
		(2, 6, 2, 1, "../../images/bologna_frosinone.jpg", "https://youtu.be/nG9rWGe0pXw?si=lsnnU0CidAIxwxuy"),
		(1, 7, 2, 0, "../../images/atalanta_genoa.jpg", "https://youtu.be/vYCj-ckjxXs?list=PL_nuaYj2IT5Nnh23tNblThcAgZAneC4W1"),
		(12, 9, 0, 1, "../../images/milan_juventus.jpg", "https://youtu.be/uPwKDNW9ylM?si=yugt6iDnXsJ-WrEw"),
		(19, 11, 1, 1, "../../images/udinese_lecce.jpg", "https://youtu.be/eWhRIwMr3U4?si=WIBV9iS_FtB7-vtZ"),
		(5, 4, 0, 2, "../../images/fiorentina_empoli.jpg", "https://youtu.be/HVw9EcNZimA?si=5bpdVzyGNNSFCCRZ"),
        
        -- DECIMA GIORNATA
        (7, 16, 1, 0, "../../images/genoa_salernitana.jpg", "https://www.youtube.com/watch?v=CVgNNSEnDWU"),
		(17, 2, 1, 1, "../../images/sassuolo_bologna.jpg", "https://www.youtube.com/watch?v=le14oFu3KFc"),
		(11, 18, 0, 1, "../../images/lecce_torino.jpg", "https://www.youtube.com/watch?v=auBOEAvQmUc"),
		(9, 20, 1, 0, "../../images/juventus_verona.jpg", "https://www.youtube.com/watch?v=EhGd5r0nv94"),
		(3, 6, 4, 3, "../../images/cagliari_frosinone.jpg", "https://www.youtube.com/watch?v=gPrDBCMnTaA"),
		(13, 19, 1, 1, "../../images/monza_udinese.jpg", "https://www.youtube.com/watch?v=5I_mGCCC9mM"),
		(8, 15, 1, 0, "../../images/inter_roma.jpg", "https://www.youtube.com/watch?v=nbEizD_3BOU"),
		(14, 12, 2, 2, "../../images/napoli_milan.jpg", "https://www.youtube.com/watch?v=D-r3eG8z8lE"),
		(4, 1, 0, 3, "../../images/empoli_atalanta.jpg", "https://www.youtube.com/watch?v=WNo7wC45Fzg"),
		(10, 5, 1, 0, "../../images/lazio_fiorentina.jpg", "https://www.youtube.com/watch?v=jFsdTeXeG7M"),
        
        -- UNDICESIMA GIORNATA
        (2, 10, 1, 0, "../../images/bologna_lazio.jpg", "https://www.youtube.com/watch?v=doB9T7MZs10"),
        (16, 14, 0, 2, "../../images/salernitana_napoli.jpg", "https://www.youtube.com/watch?v=I9myTrAaZV8"),
		(1, 8, 1, 2, "../../images/atalanta_inter.jpg", "https://www.youtube.com/watch?v=XWwV3ezwlk0&pp=ygUSYXRhbGFudGEgaW50ZXIgMSAy"),
		(12, 19, 0, 1, "../../images/milan_udinese.jpg", "https://www.youtube.com/watch?v=qkmFNnaqDkc&pp=ygURbWlsYW4gdWRpbmVzZSAwIDE%3D"),
		(20, 13, 1, 3, "../../images/verona_monza.jpg", "https://www.youtube.com/watch?v=7rXaJW7O6uM"),
		(3, 7, 2, 1, "../../images/cagliari_genoa.jpg", "https://www.youtube.com/watch?v=xnwsIMje_H4"),
		(15, 11, 2, 1, "../../images/roma_lecce.jpg", "https://www.youtube.com/watch?v=_Hmeev9LEb8"),
		(5, 9, 0, 1, "../../images/fiorentina_juventus.jpg", "https://www.youtube.com/watch?v=OANtWsXiXB8&pp=ygUYZmlvcmVucmluYSBqdXZlbnR1cyAwIDEg"),
		(6, 4, 2, 1, "../../images/frosinone_empoli.jpg", "https://www.youtube.com/watch?v=ZrpEoU7Ipe8&pp=ygUUZnJvc2lub25lIGVtcG9saSAyIDE%3D"),
		(18, 17, 2, 1, "../../images/torino_sassuolo.jpg", "https://www.youtube.com/watch?v=RVuF1Re3vj8&pp=ygUUdG9yaW5vIHNhc3N1b2xvIDIgIDE%3D"),
        
        -- DODICESIMA GIORNATA
        (17, 16, 2, 2, "../../images/sassuolo_salernitana.jpg", "https://www.youtube.com/watch?v=i5jME5hNBZw&pp=ygUZc2Fzc3VvbG8gc2FsZXJuaXRhbmEgMiAyIA%3D%3D"),
        (7, 20, 1, 0, "../../images/genoa_verona.jpg", "https://www.youtube.com/watch?v=Iis5Ee83UWo&pp=ygUQZ2Vub2EgdmVyb25hIDEgMA%3D%3D"),
		(11, 12, 2, 2, "../../images/lecce_milan.jpg", "https://www.youtube.com/watch?v=RlxKyKniQMg&pp=ygUQbGVjY2UgbWlsYW4gMiAyIA%3D%3D"),
		(9, 3, 2, 1, "../../images/juventus_cagliari.jpg", "https://www.youtube.com/watch?v=OPQE8-Vg_94&pp=ygUVanV2ZW50dXMgY2FnbGlhcmkgMiAx"),
		(13, 18, 1, 1, "../../images/monza_torino.jpg", "https://www.youtube.com/watch?v=os7xqqIKSFE&pp=ygURbW9uemEgdG9yaW5vIDEgIDE%3D"),
		(14, 4, 0, 1, "../../images/napoli_empoli.jpg", "https://www.youtube.com/watch?v=41wtrgQV2cE&pp=ygURbmFwb2xpIGVtcG9saSAwIDE%3D"),
		(5, 2, 2, 1, "../../images/fiorentina_bologna.jpg", "https://www.youtube.com/watch?v=3GWzz_Z6l2U&pp=ygUWZmlvcmVudGluYSBib2xvZ25hIDIgMQ%3D%3D"),
		(19, 1, 1, 1, "../../images/udinese_atalanta.jpg", "https://www.youtube.com/watch?v=YAbkxRhODmA&pp=ygUhdWRpbmVzZSBhdGFsYW50YSAxIDEgcmFkaW9jcm9uYWNh"),
		(10, 15, 0, 0, "../../images/lazio_roma.jpg", "https://www.youtube.com/watch?v=i8O93qzX55Q&pp=ygUObGF6aW8gcm9tYSAwIDA%3D"),
		(8, 6, 2, 0, "../../images/inter_frosinone.jpg", "https://www.youtube.com/watch?v=rVXsvEJ4Mm8&pp=ygUTaW50ZXIgZnJvc2lub25lIDIgMA%3D%3D"),
        
        -- TREDICESIMA GIORNATA
        (16, 10, 2, 1, "../../images/salernitana_lazio.jpg", "https://www.youtube.com/watch?v=MtvCCX7K66Y&pp=ygUWc2FsZXJuaXRhbmEgbGF6aW8gMiAxIA%3D%3D"),
        (1, 14, 1, 2, "../../images/atalanta_napoli.jpg", "https://www.youtube.com/watch?v=J_kwtkgmgeQ&pp=ygUTYXRhbGFudGEgbmFwb2xpIDEgMg%3D%3D"),
		(12, 5, 1, 0, "../../images/milan_fiorentina.jpg", "https://www.youtube.com/watch?v=GMqJRxgJ7xI&pp=ygUUbWlsYW4gZmlvcmVudGluYSAxIDA%3D"),
		(3, 13, 1, 1, "../../images/cagliari_monza.jpg", "https://www.youtube.com/watch?v=_Y_08rbV8AU&pp=ygUSY2FnbGlhcmkgbW9uemEgMSAx"),
		(6, 7, 2, 1, "../../images/frosinone_genoa.jpg", "https://www.youtube.com/watch?v=0kXQew-uNOM&pp=ygUUZnJvc2lub25lIGdlbm9hIDIgMSA%3D"),
		(4, 17, 3, 4, "../../images/empoli_sassuolo.jpg", "https://www.youtube.com/watch?v=WhGSXTM4rlI&pp=ygUTZW1wb2xpIHNhc3N1b2xvIDMgNA%3D%3D"),
		(15, 19, 3, 1, "../../images/roma_udinese.jpg", "https://www.youtube.com/watch?v=r2V8Cs6-1Ig&pp=ygURcm9tYSB1ZGluZXNlICAzIDE%3D"),
		(9, 8, 1, 1, "../../images/juventus_inter.jpg", "https://www.youtube.com/watch?v=wbHTAgCYYFs&pp=ygUSanV2ZW50dXMgaW50ZXIgMSAx"),
		(20, 11, 2, 2, "../../images/verona_lecce.jpg", "https://www.youtube.com/watch?v=lOFH9-OFTwQ&pp=ygUQdmVyb25hIGxlY2NlIDIgMg%3D%3D"),
		(2, 18, 2, 0, "../../images/bologna_torino.jpeg", "https://www.youtube.com/watch?v=8mfRxDwd8_s&pp=ygUSYm9sb2duYSB0b3Jpbm8gMiAw"),
        
        -- QUATTORDICESIMA GIORNATA
        (13, 9, 1, 2, "../../images/monza_juventus.jpg", "https://youtu.be/7L-eDzHz8EM?si=YoDFDwFzTvWJyrKZ"),
        (7, 4, 1, 1, "../../images/genoa_empoli.jpg", "https://youtu.be/8KicT0jvmOs?si=5BCEwnQ5If8pirqA"),
		(10, 3, 1, 0, "../../images/lazio_cagliari.jpg", "https://youtu.be/_d29ukDn42E?si=Tm7blOcnn8fH-cKv"),
		(12, 6, 3, 1, "../../images/milan_frosinone.jpg", "https://www.youtube.com/watch?v=6YT5vCEzKJc"),
		(11, 2, 1, 1, "../../images/lecce_bologna.jpg", "https://www.youtube.com/watch?v=pM9Clb2Srxg"),
		(5, 16, 3, 0, "../../images/fiorentina_salernitana.jpg", "https://www.youtube.com/watch?v=GEbbZz0GQDI&pp=ygUaZmlvcmVudGluYSBzYWxlcm5pdGFuYSAzIDA%3D"),
		(19, 20, 3, 3, "../../images/udinese_verona.jpg", "https://www.youtube.com/watch?v=HyEY8v1pf0M&pp=ygUTdWRpbmVzZSB2ZXJvbmEgMyAzIA%3D%3D"),
		(17, 15, 1, 2, "../../images/sassuolo_roma.jpg", "https://www.youtube.com/watch?v=15JclntE1pk&pp=ygURc2Fzc3VvbG8gcm9tYSAxIDI%3D"),
		(14, 8, 0, 3, "../../images/napoli_inter.jpg", "https://www.youtube.com/watch?v=tLaJgIOMVto&pp=ygUQbmFwb2xpIGludGVyIDAgMw%3D%3D"),
		(18, 1, 3, 0, "../../images/torino_atalanta.jpg", "https://www.youtube.com/watch?v=CS8Qp_0Gnkk&pp=ygUgdG9yaW5vIGF0YWxhbnRhIDMgMCByYWRpb2Nyb25hY2E%3D"),
        
        -- QUINDICESIMA GIORNATA
        (9, 14, 1, 0, "../../images/juventus_napoli.jpg", "https://www.youtube.com/watch?v=d5PrOuTDRPI&pp=ygUZanV2ZW50dXMgbmFwb2xpIDEgMCAwOC8xMg%3D%3D"),
        (20, 10, 1, 1, "../../images/verona_lazio.jpg", "https://www.youtube.com/watch?v=uPP9Jb-qt04&pp=ygURdmVyb25hIGxhemlvIDEgMSA%3D"),
		(1, 12, 3, 2, "../../images/atalanta_milan.jpg", "https://www.youtube.com/watch?v=nMYaDLZbj3c&pp=ygUSYXRhbGFudGFfbWlsYW4gMyAy"),
		(8, 19, 4, 0, "../../images/inter_udinese.jpg", "https://www.youtube.com/watch?v=PEF8y1CLyG8&pp=ygURaW50ZXIgdWRpbmVzZSA0IDA%3D"),
		(6, 18, 0, 0, "../../images/frosinone_torino.jpg", "https://www.youtube.com/watch?v=bz0Cy95At8I&pp=ygUVZnJvc2lub25lX3RvcmlubyAwIDAg"),
		(13, 7, 1, 0, "../../images/monza_genoa.jpg", "https://www.youtube.com/watch?v=rO7UQJg5gGM&pp=ygUPbW9uemEgZ2Vub2EgMSAw"),
		(16, 2, 1, 2, "../../images/salernitana_bologna.jpg", "https://www.youtube.com/watch?v=3fKrSxsqOho&pp=ygUXc2FsZXJuaXRhbmFfYm9sb2duYSAxIDI%3D"),
		(15, 5, 1, 1, "../../images/roma_fiorentina.jpg", "https://www.youtube.com/watch?v=S5KqEVkXkmQ&pp=ygUTcm9tYSBmaW9yZW50aW5hIDEgMQ%3D%3D"),
		(4, 11, 1, 1, "../../images/empoli_lecce.jpg", "https://www.youtube.com/watch?v=PlYXbEF2Huk&pp=ygUMZW1wb2xpX2xlY2Nl"),
		(3, 17, 2, 1, "../../images/cagliari_sassuolo.jpg", "https://www.youtube.com/watch?v=ZBs81CY9Y4c&pp=ygUVY2FnbGlhcmkgc2Fzc3VvbG8gMiAx"),
        
        -- SEDICESIMA GIORNATA
        (7, 9, 1, 1, "../../images/genoa_juventus.jpg", "https://www.youtube.com/watch?v=tDydME1wI7g&pp=ygUSZ2Vub2EganV2ZW50dXMgMSAx"),
        (11, 6, 2, 1, "../../images/lecce_frosinone.jpg", "https://www.youtube.com/watch?v=u9Nuiybnc30&pp=ygUTbGVjY2UgZnJvc2lub25lIDIgMQ%3D%3D"),
		(14, 3, 2, 1, "../../images/napoli_cagliari.jpg", "https://www.youtube.com/watch?v=WQaS45UcIQQ&pp=ygUTbmFwb2xpIGNhZ2xpYXJpIDIgMQ%3D%3D"),
		(18, 4, 1, 0, "../../images/torino_empoli.jpg", "https://www.youtube.com/watch?v=NNdP8zjb7No&pp=ygURdG9yaW5vIGVtcG9saSAxIDA%3D"),
		(12, 13, 3, 0, "../../images/milan_monza.jpg", "https://www.youtube.com/watch?v=8juJgVJ-Ips&pp=ygUPbWlsYW5fbW9uemEgMyAw"),
		(19, 17, 2, 2, "../../images/udinese_sassuolo.jpg", "https://www.youtube.com/watch?v=0U6U54kGgjI&pp=ygUVdWRpbmVzZSBzYXNzdW9sbyAyIDIg"),
		(5, 20, 1, 0, "../../images/fiorentina_verona.jpg", "https://www.youtube.com/watch?v=8_GV-rDryzI&pp=ygUVZmlvcmVudGluYSB2ZXJvbmEgMSAw"),
		(2, 15, 2, 0, "../../images/bologna_roma.jpg", "https://www.youtube.com/watch?v=9ueb3mSR4GA&pp=ygUQYm9sb2duYSByb21hIDIgMA%3D%3D"),
		(10, 8, 0, 2, "../../images/lazio_inter.jpg", "https://www.youtube.com/watch?v=b37DrtTbqLs&pp=ygUPbGF6aW8gaW50ZXIgMCAy"),
		(1, 16, 4, 1, "../../images/atalanta_salernitana.jpg", "https://www.youtube.com/watch?v=H2xir_xB9A8&pp=ygUYYXRhbGFudGEgc2FsZXJuaXRhbmEgNCAx"),
        
        -- DICIASSETTESIMA GIORNATA
        (17, 7, 1, 2, "../../images/sassuolo_genoa.jpg", "https://www.youtube.com/watch?v=Cv5gOD5KZ7A&pp=ygUSc2Fzc3VvbG8gZ2Vub2EgMSAy"),
        (4, 10, 0, 2, "../../images/empoli_lazio.jpg", "https://www.youtube.com/watch?v=UH6TYmvi3L0&pp=ygUQZW1wb2xpIGxhemlvIDAgMg%3D%3D"),
		(13, 5, 0, 1, "../../images/monza_fiorentina.jpg", "https://www.youtube.com/watch?v=UkBNG7IkiNY&pp=ygUUbW9uemEgZmlvcmVudGluYSAwIDE%3D"),
		(16, 12, 2, 2, "../../images/salernitana_milan.jpg", "https://www.youtube.com/watch?v=GLnszhWb0G8&pp=ygUVc2FsZXJuaXRhbmEgbWlsYW4gMiAy"),
		(6, 9, 1, 2, "../../images/frosinone_juventus.jpg", "https://www.youtube.com/watch?v=TeDHV2fzirI&pp=ygUWZnJvc2lub25lIGp1dmVudHVzIDEgMg%3D%3D"),
		(2, 1, 1, 0, "../../images/bologna_atalanta.jpg", "https://www.youtube.com/watch?v=1za2iqotiJA&pp=ygUfYm9sb2duYSBhdGFsYW50YSAxIDAgMjMvMTIvMjAyMw%3D%3D"),
		(18, 19, 1, 1, "../../images/torino_udinese.jpg", "https://www.youtube.com/watch?v=DA-UIwfJOWo&pp=ygUfdG9yaW5vIHVkaW5lc2UgMSAxIHJhZGlvY3JvbmFjYQ%3D%3D"),
		(20, 3, 2, 0, "../../images/verona_cagliari.jpg", "https://www.youtube.com/watch?v=EnHH_rMj6mg&pp=ygUTdmVyb25hIGNhZ2xpYXJpIDIgMA%3D%3D"),
		(8, 11, 2, 0, "../../images/inter_lecce.jpg", "https://www.youtube.com/watch?v=X2csadO48pY&pp=ygUOaW50ZXIgbGVjY2UyIDA%3D"),
		(15, 14, 2, 0, "../../images/roma_napoli.jpg", "https://www.youtube.com/watch?v=JFLgPB418yg&pp=ygUPcm9tYSBuYXBvbGkgMiAw"),
        
        -- DICIOTTESIMA GIORNATA
        (14, 13, 0, 0, "../../images/napoli_monza.jpg", "https://www.youtube.com/watch?v=P6nevB5lktk&pp=ygUQbmFwb2xpIG1vbnphIDAgMA%3D%3D"),
        (5, 18, 1, 0, "../../images/fiorentina_torino.jpg", "https://www.youtube.com/watch?v=j-Ul7ZsWzLo&pp=ygUVZmlvcmVudGluYSB0b3Jpbm8gMS0w"),
		(7, 8, 1, 1, "../../images/genoa_inter.jpg", "https://www.youtube.com/watch?v=ZuLsb6Q4QmI&pp=ygUPZ2Vub2EgaW50ZXIgMSAx"),
		(10, 6, 3, 1, "../../images/lazio_frosinone.jpg", "https://www.youtube.com/watch?v=qg1B2PWdEA0&pp=ygUcbGF6aW8gZnJvc2lub25lIDMgMSAyOS8xMi8yMw%3D%3D"),
		(1, 11, 1, 0, "../../images/atalanta_lecce.jpg", "https://youtu.be/sV9fGQXWXVs?list=PLcaM254yvxYr0nThQ0fdWM7zwiB0jZEDO"),
		(19, 2, 3, 0, "../../images/udinese_bologna.jpg", "https://www.youtube.com/watch?v=rnWrAPeY9kM&pp=ygUTdWRpbmVzZSBib2xvZ25hIDMgMA%3D%3D"),
		(3, 4, 0, 0, "../../images/cagliari_empoli.jpg", "https://www.youtube.com/watch?v=Gc1Q8ufpCuU&pp=ygUTY2FnbGlhcmkgZW1wb2xpIDAgMA%3D%3D"),
		(20, 16, 0, 1, "../../images/verona_salernitana.jpg", "https://www.youtube.com/watch?v=Ve07YLD4eT0&pp=ygUXdmVyb25hIHNhbGVybml0YW5hIDAtMSA%3D"),
		(12, 17, 1, 0, "../../images/milan_sassuolo.jpg", "https://www.youtube.com/watch?v=ONn3REtk0k4&pp=ygUSbWlsYW4gc2Fzc3VvbG8gMSAw"),
		(9, 15, 1, 0, "../../images/juventus_roma.jpg", "https://www.youtube.com/watch?v=KT1QOqX6mGo&pp=ygURanV2ZW50dXMgcm9tYSAxIDA%3D"),
        
        -- DICIANNOVESIMA GIORNATA
        (2, 7, 1, 1, "../../images/bologna_genoa.jpg", "https://www.youtube.com/watch?v=OiQ2DweTuFk&pp=ygURYm9sb2duYSBnZW5vYSAxIDE%3D"),
        (8, 20, 2, 1, "../../images/inter_verona.jpg", "https://www.youtube.com/watch?v=-fN4Htx7aeo&pp=ygUQaW50ZXIgdmVyb25hIDIgMQ%3D%3D"),
		(6, 13, 2, 3, "../../images/frosinone_monza.jpg", "https://www.youtube.com/watch?v=65yvWWS8R6g&pp=ygUTZnJvc2lub25lIG1vbnphIDIgMw%3D%3D"),
		(11, 3, 1, 1, "../../images/lecce_cagliari.jpg", "https://www.youtube.com/watch?v=00QVn0A_O5I&pp=ygUTbGVjY2UgY2FnbGlhcmkgMSAxIA%3D%3D"),
		(17, 5, 1, 0, "../../images/sassuolo_fiorentina.jpg", "https://www.youtube.com/watch?v=lk1GMOctJng&pp=ygUXc2Fzc3VvbG8gZmlvcmVudGluYSAxIDA%3D"),
		(4, 12, 0, 3, "../../images/empoli_milan.jpg", "https://www.youtube.com/watch?v=ahjHuVL5_C4&pp=ygUQZW1wb2xpIG1pbGFuIDAgMw%3D%3D"),
		(19, 10, 1, 2, "../../images/udinese_lazio.jpg", "https://www.youtube.com/watch?v=2LwXsSvIAxY&pp=ygURdWRpbmVzZSBsYXppbyAxIDI%3D"),
		(18, 14, 3, 0, "../../images/torino_napoli.jpg", "https://www.youtube.com/watch?v=DoKCoowb_K4&pp=ygUbdG9yaW5vIG5hcG9saSAzIDAgc3NjbmFwb2xp"),
		(16, 9, 1, 2, "../../images/salernitana_juventus.jpg", "https://www.youtube.com/watch?v=bHn6_DzYZhM&pp=ygUUc2FsZXJuaXRhbmEganV2ZSAxIDI%3D"),
		(15, 1, 1, 1, "../../images/roma_atalanta.jpg", "https://www.youtube.com/watch?v=-t0C0cso_cM&pp=ygUScm9tYSBhdGFsYW50YSAxIDEg"),
        
        -- VENTESIMA GIORNATA
        (14, 16, 2, 1, "../../images/napoli_salernitana.jpg", "https://www.youtube.com/watch?v=dRHXcdBFblk&pp=ygUWbmFwb2xpIHNhbGVybml0YW5hIDIgMQ%3D%3D"),
        (7, 18, 0, 0, "../../images/genoa_torino.jpg", "https://www.youtube.com/watch?v=ltMlpX3BXG4&pp=ygUcZ2Vub2EgdG9yaW5vIDAtMCBoaWdobGlnaHRzIA%3D%3D"),
		(20, 4, 2, 1, "../../images/verona_empoli.jpg", "https://www.youtube.com/watch?v=DGvQcrS2PSQ&pp=ygUNdmVyb25hIGVtcG9saQ%3D%3D"),
		(13, 8, 1, 5, "../../images/monza_inter.jpg", "https://www.youtube.com/watch?v=gThz2bzrhQA&pp=ygULbW9uemEgaW50ZXI%3D"),
		(10, 11, 1, 0, "../../images/lazio_lecce.jpg", "https://www.youtube.com/watch?v=U9LkrVK78xA&pp=ygUabGF6aW8gbGVjY2UgMSAwIGhpZ2hsaWdodHM%3D"),
		(3, 2, 2, 1, "../../images/cagliari_bologna.jpg", "https://www.youtube.com/watch?v=1aa4_Vl4Nlc&pp=ygUQY2FnbGlhcmkgYm9sb2duYQ%3D%3D"),
		(5, 19, 2, 2, "../../images/fiorentina_udinese.jpg", "https://www.youtube.com/watch?v=LGMvr6VDpw8&pp=ygUXZmlvcmVudGluYSB1ZGluZXNlIDIgMiA%3D"),
		(12, 15, 3, 1, "../../images/milan_roma.jpg", "https://www.youtube.com/watch?v=VcRBSI8vbJ8&pp=ygUObWlsYW4gcm9tYSAzIDE%3D"),
		(1, 6, 5, 0, "../../images/atalanta_frosinone.jpg", "https://www.youtube.com/watch?v=OkpS0s3nELU&pp=ygUWYXRhbGFudGEgZnJvc2lub25lIDUgMA%3D%3D"),
		(9, 17, 3, 0, "../../images/juventus_sassuolo.jpg", "https://www.youtube.com/watch?v=2zQvFYhPudY&pp=ygUVanV2ZW50dXMgc2Fzc3VvbG8gMyAw"),
        
        -- VENTUNESIMA GIORNATA
        (15, 20, 2, 1, "../../images/roma_verona.jpg", "https://www.youtube.com/watch?v=Y084hhY5vmw&pp=ygULcm9tYSB2ZXJvbmE%3D"),
        (19, 12, 2, 3, "../../images/udinese_milan.jpg", "https://www.youtube.com/watch?v=9DkBrr5t-P4&pp=ygUNdWRpbmVzZSBtaWxhbg%3D%3D"),
		(6, 3, 3, 1, "../../images/frosinone_cagliari.jpg", "https://www.youtube.com/watch?v=WzoUe6-J37I&pp=ygUSZnJvc2lub25lIGNhZ2xpYXJp"),
		(4, 13, 3, 0, "../../images/empoli_monza.jpg", "https://www.youtube.com/watch?v=bH3LeICHxb4&pp=ygUMZW1wb2xpIG1vbnph"),
		(16, 7, 1, 2, "../../images/salernitana_genoa.jpg", "https://www.youtube.com/watch?v=lesxx9jQ6KY&pp=ygURc2FsZXJuaXRhbmEgZ2Vub2E%3D"),
		(11, 9, 0, 3, "../../images/lecce_juventus.jpg", "https://www.youtube.com/watch?v=QgY9FLkpsY4&pp=ygUSbGVjY2UganV2ZW50dXMgMCAz"),
		(2, 5, 2, 0, "../../images/bologna_fiorentina.jpg", "https://www.youtube.com/watch?v=2H4MGyr8Ras&pp=ygUWYm9sb2duYSBmaW9yZW50aW5hIDIgMA%3D%3D"),
		(18, 10, 0, 2, "../../images/torino_lazio.jpg", "https://www.youtube.com/watch?v=fgCn45PR348&pp=ygUQdG9yaW5vIGxhemlvIDAgMg%3D%3D"),
		(17, 14, 1, 6, "../../images/sassuolo_napoli.jpg", "https://www.youtube.com/watch?v=g6XxEHesUI8&pp=ygUPc2Fzc3VvbG8gbmFwb2xp"),
		(8, 1, 4, 0, "../../images/inter_atalanta.jpg", "https://www.youtube.com/watch?v=mpGD8v3AO-c&pp=ygUOaW50ZXIgYXRhbGFudGE%3D"),

		-- VENTIDUESIMA GIORNATA
        (3, 18, 1, 2, "../../images/cagliari_torino.jpg", "https://www.youtube.com/watch?v=tbShyxhyb3Q&pp=ygUTY2FnbGlhcmkgdG9yaW5vIDEgMg%3D%3D"),	
        (1, 19, 2, 0, "../../images/atalanta_udinese.jpg", "https://www.youtube.com/watch?v=1xVyyCV_CAE&pp=ygUhYXRhbGFudGEgdWRpbmVzZSAyIDAgcmFkaW9jcm9uYWNh"),
		(9, 4, 1, 1, "../../images/juventus_empoli.jpg", "https://www.youtube.com/watch?v=2b9-CJljlVw&pp=ygUeanV2ZW50dXMgZW1wb2xpIDEgMSBoaWdobGlnaHRz"),
		(12, 2, 2, 2, "../../images/milan_bologna.jpg", "https://www.youtube.com/watch?v=NUXq_CD_gFg&pp=ygURbWlsYW4gYm9sb2duYSAyIDI%3D"),
		(7, 11, 2, 1, "../../images/genoa_lecce.jpg", "https://www.youtube.com/watch?v=ZnDZhqKv_o8&pp=ygUPZ2Vub2EgbGVjY2UgMiAx"),
		(20, 6, 1, 1, "../../images/verona_frosinone.jpg", "https://www.youtube.com/watch?v=HfEDinQ7kzU&pp=ygUVdmVyb25hIGZyb3Npbm9uZSAxIDEg"),
		(13, 17, 1, 0, "../../images/monza_sassuolo.jpg", "https://www.youtube.com/watch?v=sDYntCsMZHc&pp=ygUSbW9uemEgc2Fzc3VvbG8gMSAw"),
		(10, 14, 0, 0, "../../images/lazio_napoli.jpg", "https://www.youtube.com/watch?v=-6-LD3FGglk&pp=ygUbbGF6aW8gbmFwb2xpIDAgMCBoaWdobGlnaHRz"),
		(5, 8, 0, 1, "../../images/fiorentina_inter.jpg", "https://www.youtube.com/watch?v=TIimaf0mXnY&pp=ygUUZmlvcmVudGluYSBpbnRlciAwIDE%3D"),
		(16, 15, 1, 2, "../../images/salernitana_roma.jpg", "https://www.youtube.com/watch?v=Q_s4ddemtWI&pp=ygUUc2FsZXJuaXRhbmEgcm9tYSAxIDI%3D"),
        
        -- VENTITREESIMA GIORNATA
        (11, 5, 3, 2, "../../images/lecce_fiorentina.jpg", "https://www.youtube.com/watch?v=tay3IoxJgNE&pp=ygUUbGVjY2UgZmlvcmVudGluYSAzIDI%3D"),
        (4, 7, 0, 0, "../../images/empoli_genoa.jpg", "https://www.youtube.com/watch?v=SD1th1sHzzk&pp=ygURZW1wb2xpIGdlbm9hIDAgMCA%3D"),
		(19, 13, 0, 0, "../../images/udinese_monza.jpg", "https://www.youtube.com/watch?v=uqEyJIBHyHo&pp=ygUSdWRpbmVzZSBtb256YSAwIDAg"),
		(6, 12, 2, 3, "../../images/frosinone_milan.jpg", "https://www.youtube.com/watch?v=IbcabTvPVgE&pp=ygUTZnJvc2lub25lIG1pbGFuIDIgMw%3D%3D"),
		(2, 17, 4, 2, "../../images/bologna_sassuolo.jpg", "https://www.youtube.com/watch?v=WFqPryZugxc&pp=ygUUYm9sb2duYSBzYXNzdW9sbyA0IDI%3D"),
		(18, 16, 0, 0, "../../images/torino_salernitana.jpg", "https://www.youtube.com/watch?v=djEMNlCmXDQ&pp=ygUWdG9yaW5vIHNhbGVybml0YW5hIDAgMA%3D%3D"),
		(14, 20, 2, 1, "../../images/napoli_verona.jpg", "https://www.youtube.com/watch?v=bfTpr2ZwoFQ&pp=ygURbmFwb2xpIHZlcm9uYSAyIDE%3D"),
		(1, 10, 3, 1, "../../images/atalanta_lazio.jpg", "https://www.youtube.com/watch?v=d60l4E8pFcg&pp=ygUgYXRhbGFudGEgbGF6aW8gMyAxIHJhZGlvY3JvbmFjYSA%3D"),
		(8, 9, 1, 0, "../../images/inter_juventus.jpg", "https://www.youtube.com/watch?v=btv8LEV_3d8&pp=ygUSaW50ZXIganV2ZW50dXMgMSAw"),
		(15, 3, 4, 0, "../../images/roma_cagliari.jpg", "https://www.youtube.com/watch?v=_puUJkSRXtU&pp=ygURcm9tYSBjYWdsaWFyaSA0IDA%3D"),
        
        -- VENTIQUATTRESIMA GIORNATA
        (16, 4, 1, 3, "../../images/salernitana_empoli.jpg", "https://www.youtube.com/watch?v=iWFEbOku0PQ&pp=ygUSc2FsZXJuaXRhbmEgZW1wb2xp"),
        (3, 10, 1, 3, "../../images/cagliari_lazio.jpg", "https://www.youtube.com/watch?v=1Lr7YGjN40E&pp=ygUSY2FnbGlhcmkgbGF6aW8gMSAz"),
		(15, 8, 2, 4, "../../images/roma_inter.jpg", "https://www.youtube.com/watch?v=Nrt-zwiDpTg&pp=ygUOcm9tYSBpbnRlciAyIDQ%3D"),
		(17, 18, 1, 1, "../../images/sassuolo_torino.jpg", "https://www.youtube.com/watch?v=Y0NwBRvnz3c&pp=ygUPc2Fzc3VvbG8gdG9yaW5v"),
		(5, 6, 5, 1, "../../images/fiorentina_frosinone.jpg", "https://www.youtube.com/watch?v=KhmPBTPk-JM&pp=ygUUZmlvcmVudGluYSBmcm9zaW5vbmU%3D"),
		(13, 20, 0, 0, "../../images/monza_verona.jpg", "https://www.youtube.com/watch?v=2cD_rmzG7ko&pp=ygUMbW9uemEgdmVyb25h"),
		(2, 11, 4, 0, "../../images/bologna_lecce.jpg", "https://www.youtube.com/watch?v=QjkLUnkhaB0&pp=ygUNYm9sb2duYSBsZWNjZQ%3D%3D"),
		(7, 1, 1, 4, "../../images/genoa_atalanta.jpg", "https://www.youtube.com/watch?v=TsV3KN8Brnk&pp=ygUSZ2Vub2EgYXRhbGFudGEgMSA0"),
		(12, 14, 1, 0, "../../images/milan_napoli.jpg", "https://www.youtube.com/watch?v=B96vvuoCNLQ&pp=ygUQbWlsYW4gbmFwb2xpIDEgMA%3D%3D"),
		(9, 19, 0, 1, "../../images/juventus_udinese.jpg", "https://www.youtube.com/watch?v=Ob6a56Lh_ts&pp=ygUfanV2ZW50dXMgdWRpbmVzZSAwIDEgaGlnaGxpZ2h0cw%3D%3D"),
        
        -- VENTICINQUESIMA GIORNATA
        (18, 11, 2, 0, "../../images/torino_lecce.jpg", "https://www.youtube.com/watch?v=quLdwRMRJc8&pp=ygUkdG9yaW5vIGxlY2NlIDIgMCBoaWdobGlnaHRzICB1c2xlY2Nl"),
        (8, 16, 4, 0, "../../images/inter_salernitana.jpg", "https://www.youtube.com/watch?v=FA38HLv9KP8&pp=ygURaW50ZXIgc2FsZXJuaXRhbmE%3D"),
		(14, 7, 1, 1, "../../images/napoli_genoa.jpg", "https://www.youtube.com/watch?v=KVDYwhQqoJw&pp=ygUQbmFwb2xpIGdlbm9hIDEgMQ%3D%3D"),
		(20, 9, 2, 2, "../../images/verona_juventus.jpg", "https://www.youtube.com/watch?v=TBMXT4OAlLs&pp=ygUUdmVyb25hIGp1dmVudHVzIDIgMiA%3D"),
		(1, 17, 3, 0, "../../images/atalanta_sassuolo.jpg", "https://www.youtube.com/watch?v=RfPOIJr5p0I&pp=ygUVYXRhbGFudGEgc2Fzc3VvbG8gMyAw"),
		(10, 2, 1, 2, "../../images/lazio_bologna.jpg", "https://www.youtube.com/watch?v=K100v8v9_Pw&pp=ygUNbGF6aW8gYm9sb2duYQ%3D%3D"),
		(19, 3, 1, 1, "../../images/udinese_cagliari.jpg", "https://www.youtube.com/watch?v=lIHzEs0hILk&pp=ygUQdWRpbmVzZSBjYWdsaWFyaQ%3D%3D"),
		(4, 5, 1, 1, "../../images/empoli_fiorentina.jpg", "https://www.youtube.com/watch?v=FofFMR1S0pU&pp=ygURZW1wb2xpIGZpb3JlbnRpbmE%3D"),
		(6, 15, 0, 3, "../../images/frosinone_roma.jpg", "https://www.youtube.com/watch?v=CwYOEtArqzY&pp=ygUOZnJvc2lub25lIHJvbWE%3D"),
		(13, 12, 4, 2, "../../images/monza_milan.jpg", "https://www.youtube.com/watch?v=iN51BdfDRks&pp=ygUPbW9uemEgbWlsYW4gNCAy"),
        
        -- VENTISEIESIMA GIORNATA
        (2, 20, 2, 0, "../../images/bologna_verona.jpg", "https://www.youtube.com/watch?v=oFBS_hETXC4&pp=ygUTYm9sb2duYSB2ZXJvbmEgMiAwIA%3D%3D"),
        (17, 4, 2, 3, "../../images/sassuolo_empoli.jpg", "https://www.youtube.com/watch?v=Viua_tTvw88&pp=ygUTc2Fzc3VvbG8gZW1wb2xpIDIgMw%3D%3D"),
		(16, 13, 0, 2, "../../images/salernitana_monza.jpg", "https://www.youtube.com/watch?v=vas7PqTvi3Q&pp=ygUVc2FsZXJuaXRhbmEgbW9uemEgMCAy"),
		(7, 19, 2, 0, "../../images/genoa_udinese.jpg", "https://www.youtube.com/watch?v=KW04gpCDTmw&pp=ygURZ2Vub2EgdWRpbmVzZSAyIDA%3D"),
		(9, 6, 3, 2, "../../images/juventus_frosinone.jpg", "https://www.youtube.com/watch?v=5Jgk8JJnjzw&pp=ygUWanV2ZW50dXMgZnJvc2lub25lIDMgMg%3D%3D"),
		(3, 14, 1, 1, "../../images/cagliari_napoli.jpg", "https://www.youtube.com/watch?v=Bz7GjCGXSL8&pp=ygUUY2FnbGlhcmkgbmFwb2xpIDEgMSA%3D"),
		(11, 8, 0, 4, "../../images/lecce_inter.jpg", "https://www.youtube.com/watch?v=DKVVJeW3sv0&pp=ygULbGVjY2UgaW50ZXI%3D"),
		(12, 1, 1, 1, "../../images/milan_atalanta.jpg", "https://www.youtube.com/watch?v=atLvTzmWH-E&pp=ygUSbWlsYW4gYXRhbGFudGEgMSAx"),
		(15, 18, 3, 2, "../../images/roma_torino.jpg", "https://www.youtube.com/watch?v=p2Yv7msjnEM&pp=ygUPcm9tYSB0b3Jpbm8gMyAy"),
		(5, 10, 2, 1, "../../images/fiorentina_lazio.jpg", "https://www.youtube.com/watch?v=GS9CYALtDBk&pp=ygUUZmlvcmVudGluYSBsYXppbyAyIDE%3D"),
        
        -- VENTISETTESIMA GIORNATA
        (10, 12, 0, 1, "../../images/lazio_milan.jpg", "https://www.youtube.com/watch?v=jyY4HWBdd-4&pp=ygUPbGF6aW8gbWlsYW4gMCAx"),
        (19, 16, 1, 1, "../../images/udinese_salernitana.jpg", "https://www.youtube.com/watch?v=PSCRe6Y9MIQ&pp=ygUXdWRpbmVzZSBzYWxlcm5pdGFuYSAxIDE%3D"),
		(13, 15, 1, 4, "../../images/monza_roma.jpg", "https://www.youtube.com/watch?v=1Z3w1b4OW70&pp=ygUObW9uemEgcm9tYSAxIDQ%3D"),
		(18, 5, 0, 0, "../../images/torino_fiorentina.jpg", "https://www.youtube.com/watch?v=Tt2WlYYOYVI&pp=ygUVdG9yaW5vIGZpb3JlbnRpbmEgMCAw"),
		(20, 17, 1, 0, "../../images/verona_sassuolo.jpg", "https://www.youtube.com/watch?v=2zi_ObUXFVg&pp=ygUTdmVyb25hIHNhc3N1b2xvIDEgMA%3D%3D"),
		(6, 11, 1, 1, "../../images/frosinone_lecce.jpg", "https://www.youtube.com/watch?v=w84Wq55S6QY&pp=ygUUZnJvc2lub25lIGxlY2NlIDEgMSA%3D"),
		(4, 3, 0, 1, "../../images/empoli_cagliari.jpg", "https://www.youtube.com/watch?v=n7U-h_rT4vo&pp=ygUTZW1wb2xpIGNhZ2xpYXJpIDAgMQ%3D%3D"),
		(1, 2, 1, 2, "../../images/atalanta_bologna.jpg", "https://www.youtube.com/watch?v=okAUZnK1q_s&pp=ygUUYXRhbGFudGEgYm9sb2duYSAxIDI%3D"),
		(14, 9, 2, 1, "../../images/napoli_juventus.jpg", "https://www.youtube.com/watch?v=sVDLjsml2xM&pp=ygUebmFwb2xpIGp1dmVudHVzIDIgMSBzc2MgbmFwb2xp"),
		(8, 7, 2, 1, "../../images/inter_genoa.jpg", "https://www.youtube.com/watch?v=WclmbplNrW8&pp=ygULaW50ZXIgZ2Vub2E%3D"),
        
        -- VENTOTTESIMA GIORNATA
        (14, 18, 1, 1, "../../images/napoli_torino.jpg", "https://www.youtube.com/watch?v=vCHw7HQCcec&pp=ygURbmFwb2xpIHRvcmlubyAxIDE%3D"),
        (17, 6, 1, 0, "../../images/sassuolo_frosinone.jpg", "https://www.youtube.com/watch?v=9LUrUl6V5wQ&pp=ygUWc2Fzc3VvbG8gZnJvc2lub25lIDEgMA%3D%3D"),
		(3, 16, 4, 2, "../../images/cagliari_salernitana.jpg", "https://www.youtube.com/watch?v=TC24MYPTSN0&pp=ygUYY2FnbGlhcmkgc2FsZXJuaXRhbmEgNCAy"),
		(2, 8, 0, 1, "../../images/bologna_inter.jpg", "https://www.youtube.com/watch?v=BflqPfp6y5w&pp=ygURYm9sb2duYSBpbnRlciAwIDE%3D"),
		(7, 13, 2, 3, "../../images/genoa_monza.jpg", "https://www.youtube.com/watch?v=t1N8PaJOWkY&pp=ygUPZ2Vub2EgbW9uemEgMiAz"),
		(11, 20, 0, 1, "../../images/lecce_verona.jpg", "https://www.youtube.com/watch?v=5Qclmnayizw&pp=ygUQbGVjY2UgdmVyb25hIDAgMQ%3D%3D"),
		(12, 4, 1, 0, "../../images/milan_empoli.jpg", "https://www.youtube.com/watch?v=Qdr2ukqj_LY&pp=ygUQbWlsYW4gZW1wb2xpIDEgMA%3D%3D"),
		(9, 1, 2, 2, "../../images/juventus_atalanta.jpg", "https://www.youtube.com/watch?v=PaYBbhGHios&pp=ygUWanV2ZW50dXMgYXRhbGFudGEgMiAyIA%3D%3D"),
		(5, 15, 2, 2, "../../images/fiorentina_roma.jpg", "https://www.youtube.com/watch?v=IXwQwq3_kO8&pp=ygUUZmlvcmVudGluYSByb21hIDIgMiA%3D"),
		(10, 19, 1, 2, "../../images/lazio_udinese.jpg", "https://www.youtube.com/watch?v=prBgwnctm4s&pp=ygURbGF6aW8gdWRpbmVzZSAxIDI%3D"),
        
        -- VENTINOVESIMA GIORNATA
        (4, 2, 0, 1, "../../images/empoli_bologna.jpg", "https://www.youtube.com/watch?v=LV5QwXCLjUw&pp=ygUSZW1wb2xpIGJvbG9nbmEgMCAx"),
        (19, 18, 0, 2, "../../images/udinese_torino.jpg", "https://www.youtube.com/watch?v=xO4Madp7NbI&pp=ygUSdWRpbmVzZSB0b3Jpbm8gMCAy"),
		(13, 3, 1, 0, "../../images/monza_cagliari.jpg", "https://www.youtube.com/watch?v=Nl9MLUIM7EA&t=5s&pp=ygUtTU9OWkEgMSAtIDAgQ0FHTElBUkkgfCBISUdITElHSFRTIFNFUklFIEEgVElN"),
		(16, 11, 0, 1, "../../images/salernitana_lecce.jpg", "https://www.youtube.com/watch?v=ZNFBUtqWn-s&pp=ygURc2FsZXJuaXRhbmEgbGVjY2U%3D"),
		(6, 10, 2, 3, "../../images/frosinone_lazio.jpg", "https://www.youtube.com/watch?v=0gOHj8jrHfo&pp=ygUTZnJvc2lub25lIGxhemlvIDIgMw%3D%3D"),
		(9, 7, 0, 0, "../../images/juventus_genoa.jpg", "https://www.youtube.com/watch?v=SaxEpIMGNWA&pp=ygUOanV2ZW50dXMgZ2Vub2E%3D"),
		(20, 12, 1, 3, "../../images/verona_milan.jpg", "https://www.youtube.com/watch?v=PorglYRTVAE&pp=ygUQdmVyb25hIG1pbGFuIDEgMw%3D%3D"),
		(15, 17, 1, 0, "../../images/roma_sassuolo.jpg", "https://www.youtube.com/watch?v=-wDlLm2O1VQ&pp=ygURcm9tYSBzYXNzdW9sbyAxIDA%3D"),
		(8, 14, 1, 1, "../../images/inter_napoli.jpg", "https://www.youtube.com/watch?v=y228D0hP5Pk&pp=ygURaW50ZXIgbmFwb2xpIDEgMSA%3D"),
        -- (1, 5, ----, ----, "../../images/atalanta_fiorentina.jpg", "")
        
        -- TRENTESIMA GIORNATA
        (14, 1, 0, 3, "../../images/napoli_atalanta.jpg", "https://www.youtube.com/watch?v=T-ciM_wEWKM&pp=ygUdbmFwb2xpIGF0YWxhbnRhIDAgMyBzc2NuYXBvbGk%3D"),
        (7, 6, 1, 1, "../../images/genoa_frosinone.jpg", "https://www.youtube.com/watch?v=UXdOd0_siYE&pp=ygUTZ2Vub2EgZnJvc2lub25lIDEgMQ%3D%3D"),
        (18, 13, 1, 0, "../../images/torino_monza.jpg", "https://www.youtube.com/watch?v=NSwhELUE5VQ&pp=ygUQdG9yaW5vIG1vbnphIDEgMA%3D%3D"),
		(10, 9, 1, 0, "../../images/lazio_juventus.jpg", "https://www.youtube.com/watch?v=koXhB-72h4g&pp=ygUSbGF6aW8ganV2ZW50dXMgMSAw"),
		(5, 12, 1, 2, "../../images/fiorentina_milan.jpg", "https://www.youtube.com/watch?v=xNLX55npXuc&pp=ygUUZmlvcmVudGluYSBtaWxhbiAxIDI%3D"),
		(2, 16, 3, 0, "../../images/bologna_salernitana.jpg", "https://www.youtube.com/watch?v=04M4c62vtTw&pp=ygUXYm9sb2duYSBzYWxlcm5pdGFuYSAzIDA%3D"),
		(3, 20, 1, 1, "../../images/cagliari_verona.jpg", "https://www.youtube.com/watch?v=pby9nNb-KOI&pp=ygUTY2FnbGlhcmkgdmVyb25hIDEgMQ%3D%3D"),
		(17, 19, 1, 1, "../../images/sassuolo_udinese.jpg", "https://www.youtube.com/watch?v=azQfMBUfNhk&pp=ygUUc2Fzc3VvbG8gdWRpbmVzZSAxIDE%3D"),
		(11, 15, 0, 0, "../../images/lecce_roma.jpg", "https://www.youtube.com/watch?v=3MefApOamuE&pp=ygUPbGVjY2Ugcm9tYSAwIDAg"),
		(8, 4, 2, 0, "../../images/inter_empoli.jpg", "https://www.youtube.com/watch?v=X1-P6MvpVKQ&pp=ygUQaW50ZXIgZW1wb2xpIDIgMA%3D%3D"),
        
        -- TRENTUNESIMA GIORNATA
		(16, 17, 2, 2, "../../images/salernitana_sassuolo.jpg", "https://www.youtube.com/watch?v=HrFaJWX_X_A&pp=ygUZc2FsZXJuaXRhbmEgc2Fzc3VvbG8gMiAgMg%3D%3D"),
        (12, 11, 3, 0, "../../images/milan_lecce.jpg", "https://www.youtube.com/watch?v=6-mHvUGfL6k&pp=ygUPbWlsYW4gbGVjY2UgMyAw"),
		(15, 10, 1, 0, "../../images/roma_lazio.jpg", "https://www.youtube.com/watch?v=DyIxr44Ytng&pp=ygUOcm9tYSBsYXppbyAxIDA%3D"),
		(4, 18, 3, 2, "../../images/empoli_torino.jpg", "https://www.youtube.com/watch?v=KcEeDDcWUPk&pp=ygURZW1wb2xpIHRvcmlubyAzIDI%3D"),
		(6, 2, 0, 0, "../../images/frosinone_bologna.jpg", "https://www.youtube.com/watch?v=eVpgLqYuHPM&pp=ygUWZnJvc2lub25lIGJvbG9nbmEgMCAwIA%3D%3D"),
		(13, 14, 2, 4, "../../images/monza_napoli.jpg", "https://www.youtube.com/watch?v=JnSb3fxKOZ0&pp=ygUQbW9uemEgbmFwb2xpIDIgNA%3D%3D"),
		(20, 7, 1, 2, "../../images/verona_genoa.jpg", "https://www.youtube.com/watch?v=GsqK0J_5IpI&pp=ygUQdmVyb25hIGdlbm9hIDEgMg%3D%3D"),
		(3, 1, 2, 1, "../../images/cagliari_atalanta.jpg", "https://www.youtube.com/watch?v=Ltb4bLpOPBQ&pp=ygUVY2FnbGlhcmkgYXRhbGFudGEgMiAx"),
		(9, 5, 1, 0, "../../images/juventus_fiorentina.jpg", "https://www.youtube.com/watch?v=SgNtRQr_Rok&pp=ygUXanV2ZW50dXMgZmlvcmVudGluYSAxIDA%3D"),
		(19, 8, 1, 2, "../../images/udinese_inter.jpg", "https://www.youtube.com/watch?v=gs6zGD8kEOQ&pp=ygURdWRpbmVzZSBpbnRlciAxIDI%3D"),
        
        -- TRENTADUESIMA GIORNATA
		(10, 16, 4, 1, "../../images/lazio_salernitana.jpg", "https://www.youtube.com/watch?v=k_p5IYSquCI&pp=ygUVbGF6aW8gc2FsZXJuaXRhbmEgNCAx"),
        (11, 4, 1, 0, "../../images/lecce_empoli.jpg", "https://www.youtube.com/watch?v=HhCWTBWc-38&pp=ygUkbGVjY2UgZW1wb2xpIDEgMCBoaWdobGlnaHRzIHVzIGxlY2Nl"),
		(18, 9, 0, 0, "../../images/torino_juventus.jpg", "https://www.youtube.com/watch?v=amlkLiDbFRQ&pp=ygUUdG9yaW5vIGp1dmVudHVzIDAgMCA%3D"),
		(2, 13, 0, 0, "../../images/bologna_monza.jpg", "https://www.youtube.com/watch?v=qAh4el8zanI&pp=ygUSYm9sb2duYSBtb256YSAwIDAg"),
		(14, 6, 2, 2, "../../images/napoli_frosinone.jpg", "https://www.youtube.com/watch?v=O31UwFWEyF4&pp=ygUVbmFwb2xpIGZyb3Npbm9uZSAyIDIg"),
		(17, 12, 3, 3, "../../images/sassuolo_milan.jpg", "https://www.youtube.com/watch?v=iqZnJCqU5Ac&pp=ygUOc2Fzc3VvbG8gbWlsYW4%3D"),
		(8, 3, 2, 2, "../../images/inter_cagliari.jpg", "https://www.youtube.com/watch?v=zz8gYqbVNMs&pp=ygUSaW50ZXIgY2FnbGlhcmkgMiAy"),
		(5, 7, 1, 1, "../../images/fiorentina_genoa.jpg", "https://www.youtube.com/watch?v=O6zMUsKcBH8&pp=ygUVZmlvcmVudGluYSBnZW5vYSAxIDEg"),
		(1, 20, 2, 2, "../../images/atalanta_verona.jpg", "https://www.youtube.com/watch?v=ainfnIFoC1c&pp=ygUUYXRhbGFudGEgdmVyb25hIDIgIDI%3D"),
		(19, 15, 1, 2, "../../images/udinese_roma.jpg", "https://www.youtube.com/watch?v=UmQoY3T0TUk&pp=ygUMdWRpbmVzZSByb21h"),
        
        -- TRENTATREESIMA GIORNATA
		(7, 10, 0, 1, "../../images/genoa_lazio.jpg", "https://www.youtube.com/watch?v=kGaephJLJ4M&pp=ygUbbGF6aW8gZ2Vub2EgMCAxIGhpZ2hsaWdodHMg"),
        (3, 9, 2, 2, "../../images/cagliari_juventus.jpg", "https://www.youtube.com/watch?v=Q7ZyFKBtNHQ&pp=ygUVY2FnbGlhcmkganV2ZW50dXMgMiAy"),
		(4, 14, 1, 0, "../../images/empoli_napoli.jpg", "https://www.youtube.com/watch?v=XUgriYI_sUc&pp=ygUSZW1wb2xpIG5hcG9saSAxIDAg"),
		(20, 19, 1, 0, "../../images/verona_udinese.jpg", "https://www.youtube.com/watch?v=eWdnSLQBUjQ&pp=ygUOdmVyb25hIHVkaW5lc2U%3D"),
		(17, 11, 0, 3, "../../images/sassuolo_lecce.jpg", "https://www.youtube.com/watch?v=024z2kQf5wg&pp=ygUac2Fzc3VvbG8gbGVjY2UgMCAzIHVzbGVjY2U%3D"),
		(18, 6, 0, 0, "../../images/torino_frosinone.jpg", "https://www.youtube.com/watch?v=dzaARMyG66E&pp=ygUVdG9yaW5vIGZyb3Npbm9uZSAwIDAg"),
		(16, 5, 0, 2, "../../images/salernitana_fiorentina.jpg", "https://www.youtube.com/watch?v=KuFvrfA0mac&pp=ygUac2FsZXJuaXRhbmEgZmlvcmVudGluYSAwIDI%3D"),
		(13, 1, 1, 2, "../../images/monza_atalanta.jpg", "https://www.youtube.com/watch?v=WUambboPg6g&pp=ygUSbW9uemEgYXRhbGFudGEgMSAy"),
		(15, 2, 1, 3, "../../images/roma_bologna.jpg", "https://www.youtube.com/watch?v=7iXX3Jq_Y3Y&pp=ygUQcm9tYSBib2xvZ25hIDEgMw%3D%3D"),
		(12, 8, 1, 2, "../../images/milan_inter.jpg", "https://www.youtube.com/watch?v=WjDr4oy6qGA&pp=ygUPbWlsYW4gaW50ZXIgMSAy"),
        
        -- TRENTAQUATTRESIMA GIORNATA
		(6, 16, 3, 0, "../../images/frosinone_salernitana.jpg", "https://www.youtube.com/watch?v=OBcAZ3g_hwA&pp=ygUtU0VSSUUgQSAnMjMvJzI0IHwgRlJPU0lOT05FIC0gU0FMRVJOSVRBTkEgMy0w"),
        (11, 13, 1, 1, "../../images/lecce_monza.jpg", "https://www.youtube.com/watch?v=Uw5Oc6934tA&pp=ygUQbGVjY2UgbW9uemEgMSAgMQ%3D%3D"),
		(9, 12, 0, 0, "../../images/juventus_milan.jpg", "https://www.youtube.com/watch?v=yO3_0oP--3U&pp=ygUSanV2ZW50dXMgbWlsYW4gMCAw"),
		(10, 20, 1, 0, "../../images/lazio_verona.jpg", "https://www.youtube.com/watch?v=Yza1VjUCGJE&pp=ygUkbGF6aW8gdmVyb25hIDEgMCBoaWdobGlnaHRzIHNzIGxhemlv"),
		(8, 18, 2, 0, "../../images/inter_torino.jpg", "https://www.youtube.com/watch?v=0rFhDqf0hsY&pp=ygUbaW50ZXIgdG9yaW5vIDEgMCBoaWdobGlnaHRz"),
		(2, 19, 1, 1, "../../images/bologna_udinese.jpg", "https://www.youtube.com/watch?v=NwORxnxKLj4&pp=ygUUYm9sb2duYSB1ZGluZXNlIDEgMSA%3D"),
		(14, 15, 2, 2, "../../images/napoli_roma.jpg", "https://www.youtube.com/watch?v=X1V1uxYFqGI&pp=ygUPbmFwb2xpIHJvbWEgMiAy"),
		(1, 4, 2, 0, "../../images/atalanta_empoli.jpg", "https://www.youtube.com/watch?v=z5-G2zxAhhk&pp=ygUTYXRhbGFudGEgZW1wb2xpIDIgMA%3D%3D"),
		(5, 17, 5, 1, "../../images/fiorentina_sassuolo.jpg", "https://www.youtube.com/watch?v=prOR_I2M9qw&pp=ygUXZmlvcmVudGluYSBzYXNzdW9sbyA1IDE%3D"),
		(7, 3, 3, 0, "../../images/genoa_cagliari.jpg", "https://www.youtube.com/watch?v=4U8HuZZe9H0&pp=ygUSZ2Vub2EgY2FnbGlhcmkgMyAw"),
        
        -- TRENTACINQUESIMA GIORNATA
		(18, 2, 0, 0, "../../images/torino_bologna.jpg", "https://www.youtube.com/watch?v=hS-KvB9rSwY&pp=ygUTdG9yaW5vIGJvbG9nbmEgMCAwIA%3D%3D"),
        (13, 10, 2, 2, "../../images/monza_lazio.jpg", "https://www.youtube.com/watch?v=w7JSgic9740&pp=ygUabW9uemEgbGF6aW8gMiAyIGhpZ2hsaWdodHM%3D"),
		(17, 8, 1, 0, "../../images/sassuolo_inter.jpg", "https://www.youtube.com/watch?v=pSuv6i1ayZE&pp=ygUUc2Fzc3VvbG8gaW50ZXIgIDEgMCA%3D"),
		(3, 11, 1, 1, "../../images/cagliari_lecce.jpg", "https://www.youtube.com/watch?v=9bO3vZcMyLs&pp=ygUTY2FnbGlhcmkgbGVjY2UgMSAxIA%3D%3D"),
		(20, 5, 2, 1, "../../images/verona_fiorentina.jpg", "https://www.youtube.com/watch?v=WJRAFhu3D2M&pp=ygUVdmVyb25hIGZpb3JlbnRpbmEgMiAx"),
		(4, 6, 0, 0, "../../images/empoli_frosinone.jpg", "https://www.youtube.com/watch?v=AB_WrfcVyJs&pp=ygUQZW1wb2xpIGZyb3Npbm9uZQ%3D%3D"),
		(12, 7, 3, 3, "../../images/milan_genoa.jpg", "https://www.youtube.com/watch?v=5kmhn6oyKxI&pp=ygUQbWlsYW4gZ2Vub2EgMyAzIA%3D%3D"),
		(15, 9, 1, 1, "../../images/roma_juventus.jpg", "https://www.youtube.com/watch?v=oE3xaHof3hQ&pp=ygUScm9tYSBqdXZlbnR1cyAxIDEg"),
		(16, 1, 1, 2, "../../images/salernitana_atalanta.jpg", "https://www.youtube.com/watch?v=2bd0ity2xa4&pp=ygUYc2FsZXJuaXRhbmEgYXRhbGFudGEgMSAy"),
		(19, 14, 1, 1, "../../images/udinese_napoli.jpg", "https://www.youtube.com/watch?v=5pIQaQR5qsY&pp=ygUddWRpbmVzZSBuYXBvbGkgMSAxIGhpZ2hsaWdodHM%3D"),
        
        -- TRENTASEIESIMA GIORNATA
		(6, 8, 0, 5, "../../images/frosinone_inter.jpg", "https://www.youtube.com/watch?v=ihRzS88dWT8&pp=ygUPZnJvc2lub25lIGludGVy"),
        (14, 2, 0, 2, "../../images/napoli_bologna.jpg", "https://www.youtube.com/watch?v=8Xnk1j4UdCM&pp=ygUSbmFwb2xpIGJvbG9nbmEgMCAy"),
		(12, 3, 5, 1, "../../images/milan_cagliari.jpg", "https://www.youtube.com/watch?v=kubN4_IP_1U&pp=ygUSbWlsYW4gY2FnbGlhcmkgNSAx"),
		(10, 4, 2, 0, "../../images/lazio_empoli.jpg", "https://www.youtube.com/watch?v=XGJkW1cNWRM&pp=ygUQbGF6aW8gZW1wb2xpIDIgMA%3D%3D"),
		(7, 17, 2, 1, "../../images/genoa_sassuolo.jpg", "https://www.youtube.com/watch?v=Mnhejm0Bp70&pp=ygUSZ2Vub2Egc2Fzc3VvbG8gMiAx"),
		(20, 18, 1, 2, "../../images/verona_torino.jpg", "https://www.youtube.com/watch?v=CQcePx07ZQA&pp=ygURdmVyb25hIHRvcmlubyAxIDI%3D"),
		(9, 16, 1, 1, "../../images/juventus_salernitana.jpg", "https://www.youtube.com/watch?v=Qzg_QPofoGw&pp=ygUYanV2ZW50dXMgc2FsZXJuaXRhbmEgMSAx"),
		(1, 15, 2, 1, "../../images/atalanta_roma.jpg", "https://www.youtube.com/watch?v=A1gomx95bbY&pp=ygUeYXRhbGFudGEgcm9tYSAyIDEgcmFkaW9jcm9uYWNh"),
		(11, 19, 0, 2, "../../images/lecce_udinese.jpg", "https://www.youtube.com/watch?v=ajmGr1nlBlk&t=6s&pp=ygURbGVjY2UgdWRpbmVzZSAwIDI%3D"),
		(5, 13, 2, 1, "../../images/fiorentina_monza.jpg", "https://www.youtube.com/watch?v=VpIYtKRjBps&pp=ygUUZmlvcmVudGluYSBtb256YSAyIDE%3D"),
        
        -- TRENTASETTESIMA GIORNATA
        (5, 14, 2, 2, "../../images/fiorentina_napoli.jpg", "https://www.youtube.com/watch?v=ep7vUzCVXSc&pp=ygUVZmlvcmVudGluYSBuYXBvbGkgMiAy"),
        (11, 1, 0, 2, "../../images/lecce_atalanta.jpg", ""),
        (18, 12, 3, 1, "../../images/torino_milan.jpg", "https://www.youtube.com/watch?v=N9HQxIIkOP8&pp=ygUbdG9yaW5vIG1pbGFuIDMgMSBoaWdobGlnaHRz"),
        (17, 3, 0, 2, "../../images/sassuolo_cagliari.jpg", "https://www.youtube.com/watch?v=YJw59wNZHrI&pp=ygUgc2Fzc3VvbG8gY2FnbGlhcmkgMCAyIGhpZ2hsaWdodHM%3D"),
        (19, 4, 1, 1, "../../images/udinese_empoli.jpg", "https://www.youtube.com/watch?v=QMraj4zDFaA&pp=ygUSdWRpbmVzZSBlbXBvbGkgMSAx"),
        (13, 6, 0, 1, "../../images/monza_frosinone.jpg", "https://www.youtube.com/watch?v=CBo9KXugOvk&pp=ygUIYWMgbW9uemE%3D"),
        (8, 10, 1, 1, "../../images/inter_lazio.jpg", "https://www.youtube.com/watch?v=LMP7s8JOgq0&pp=ygUQaW50ZXIgbGF6aW8gMSAxIA%3D%3D"),
        (15, 7, 1, 0, "../../images/roma_genoa.jpg", "https://www.youtube.com/watch?v=uIoF_GxDNno&pp=ygUOcm9tYSBnZW5vYSAxIDA%3D"),
        (16, 20, 1, 2, "../../images/salernitana_verona.jpg", "https://www.youtube.com/watch?v=4Mqiuw5vTYw&pp=ygUWc2FsZXJuaXRhbmEgdmVyb25hIDEgMg%3D%3D"),
        (2, 9, 3, 3, "../../images/bologna_juventus.jpg", "https://www.youtube.com/watch?v=iaGjlb-Oekg&pp=ygUUYm9sb2duYSBqdXZlbnR1cyAzIDM%3D"),
        
        -- TRENTOTTESIMA GIORNATA
        (3, 5, 2, 3, "../../images/cagliari_fiorentina.jpg", "https://www.youtube.com/watch?v=AY8cMiyRKag&pp=ygUeaGlnaGxpZ2h0cyBjYWdsaWFyaSBmaW9yZW50aW5h"),
        (7, 2, 2, 0, "../../images/genoa_bologna.jpg", "https://www.youtube.com/watch?v=IcEMBHCDPUo&pp=ygUYZ2Vub2EgYm9sb2duYSBoaWdobGlnaHRz"),
        (9, 13, 2, 0, "../../images/juventus_monza.jpg", "https://www.youtube.com/watch?v=efW7jY_29kY&pp=ygUZanV2ZW50dXMgbW9uemEgaGlnaGxpZ2h0cw%3D%3D"),
        (12, 16, 3, 3, "../../images/milan_salernitana.jpg", "https://www.youtube.com/watch?v=zaC7FPvpK6Q&pp=ygUcbWlsYW4gc2FsZXJuaXRhbmEgaGlnaGxpZ2h0cw%3D%3D");
        -- (4, 15, ---, ---, "../../images/empoli_roma.jpg", ""),
        -- (1, 18, ---, ---, "../../images/atalanta_torino.jpg", ""),
        -- (14, 11, ---, ---, "../../images/napoli_lecce.jpg", ""),
        -- (6, 19, ---, ---, "../../images/frosinone_udinese.jpg", ""),
        -- (20, 8, ---, ---, "../../images/verona_inter.jpg", ""),
        -- (10, 17, ---, ---, "../../images/lazio_sassuolo.jpg", "");